# Site settings
title: Sangnu
email: sangnu@linux.es
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/"
url: "https://sangnu.github.io"
twitter_username: sangnu
github_username:  sangnu

# Build settings
markdown: kramdown
theme: jekyll-theme-architect
plugins:
  - jekyll-feed

 exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
